// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AutoImportFile(arg1) {
  return window['go']['main']['App']['AutoImportFile'](arg1);
}

export function ExplainQuery(arg1) {
  return window['go']['main']['App']['ExplainQuery'](arg1);
}

export function ExportReport(arg1, arg2) {
  return window['go']['main']['App']['ExportReport'](arg1, arg2);
}

export function GetRecord(arg1) {
  return window['go']['main']['App']['GetRecord'](arg1);
}

export function GetStats() {
  return window['go']['main']['App']['GetStats']();
}

export function GetSupportedParserTypes() {
  return window['go']['main']['App']['GetSupportedParserTypes']();
}

export function GetTimeline(arg1) {
  return window['go']['main']['App']['GetTimeline'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ImportFile(arg1, arg2) {
  return window['go']['main']['App']['ImportFile'](arg1, arg2);
}

export function Query(arg1) {
  return window['go']['main']['App']['Query'](arg1);
}

export function SelectLogFile() {
  return window['go']['main']['App']['SelectLogFile']();
}
